name: Remote SSH commands

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The type of machine to run the job on

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Install SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.MY_SECRET_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Execute commands over SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.201.51.73 << EOF
        cd AWS-ECS-CI-CD 
        git pull 
        sudo docker stop flask 
        sudo docker rm flask 
        sudo docker build -t flask . 
        sudo docker run flask -d -p 5000:5000
        EOF
